name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==21.0.1
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 wordicum --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 wordicum --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: Test with pytest
      run: |
        pytest
